---
- name: Install Plone with ansible
  hosts:
    - localhost
  connection: local
  vars:
    plone_install_dir: "{{ ansible_facts.env.PWD }}"
    plone_version: 6.0.12
    plone_python: python3.11

  tasks:
    - name: Check if we have custom defined variables
      ansible.builtin.include_vars:
        dir: etc/ansible
      tags:
        - always

    - name: Install the plone virtualenv
      collective.plonestack.plone_venv:
        target: "{{ plone_install_dir }}"
        plone_version: "{{ plone_version }}"
        python_version: "{{ plone_python }}"
      tags:
        - virtualenv

    - name: "Install the zeo server"
      collective.plonestack.plone_zeoserver:
        target: "{{ plone_install_dir }}"
      tags:
        - zeo

    - name: "Install the zeo clients"
      collective.plonestack.plone_zeoinstance:
        target: "{{ plone_install_dir }}"

    # - name: "Configure supervisor"
    #   collective.plonsestack.plone_supervisor:
    #     programs: []
