---
- name: "Install Plone with ansible"
  hosts:
    - localhost
  connection: local
  vars:
    plone_install_dir: '{{ ansible_facts.env.PWD }}'
    plone_version: 6.0.12
    plone_python: 3.11

  tasks:
    - name: "Check if we have custom defined variables"
      ansible.builtin.include_vars:
        dir: etc/ansible
      tags:
        - always

    - name: "Install the plone virtualenv"
      collective.plonestack.plone_venv:
        target: '{{ plone_install_dir }}'
        plone_version: '{{ plone_version }}'
        python_version: '{{ plone_python }}'
        extra_requirements:
          - collective.pdbpp
          - collective.icecream
        extra_constraints:
          asttokens: 2.4.1
          collective.icecream: 1.0.0a1
          collective.pdbpp: 1.0.0a2
          executing: 2.0.1
          icecream: 2.1.3
          lxml_html_clean: 0.1.1
          supervisor: 4.2.5
          uv: 0.3.2
        source_checkouts:
          - name: plonetheme.enisa
            repo: git@github.com:enisaeu/plonetheme.enisa.git
            version: plone6
      tags:
        - virtualenv

    - name: "Install the zeo server"
      collective.plonestack.plone_zeoserver:
        target: '{{ plone_install_dir }}'
      tags:
        - zeo

    - name: "Install the zeo clients"
      collective.plonestack.plone_zeoinstance:
        target: '{{ plone_install_dir }}'
        instances:
          - name: 'instance'
            skip_supervisor: true
        environment_vars: |
          zope_i18n_compile_mo_files true
          CHAMELEON_CACHE {{ plone_install_dir }}/var/cache
          DIAZO_ALWAYS_CACHE_RULES true
          PTS_LANGUAGES en

    - name: "Configure supervisor"
      collective.plonestack.plone_supervisor:
        target: '{{ plone_install_dir }}'
