---
- name: "Install Plone with ansible"
  hosts:
    - localhost
  connection: local
  roles:
    - role: collective.plonestack.deploy_plone
      vars:
        deploy_plone_target: "{{ ansible_env.PWD }}/var/plone"
        deploy_plone_ansible_etc_dir: "{{ ansible_env.PWD }}/etc/ansible"
