---
- name: 'Install Plone with ansible'
  hosts:
    - localhost
  connection: 'local'
  vars:
    plone_install_dir: '{{ ansible_facts.env.PWD }}'
    plone_version: 6.0.11.1
    plone_python: python3.11
    plone_base_port: 8080
    plone_workers: 2
    plone_worker_instance: false
    zeo_address: '{{ plone_install_dir }}/var/zeo/zeo.sock'
  tasks:
    - name: 'Check if we have custom defined variables'
      ansible.builtin.include_vars:
        dir: etc/ansible
      tags:
        - always

    - name: 'Run the tasks from the role plone_virtualenv'
      ansible.builtin.include_role:
        name: plone_virtualenv

    - name: 'Run the tasks from the role plone_zeo'
      ansible.builtin.include_role:
        name: plone_zeo

    - name: 'Run the tasks from the role plone_instance'
      ansible.builtin.include_role:
        name: plone_instance

    - name: 'Create the instance workers'
      ansible.builtin.include_role:
        name: plone_instance
      loop: '{{ range(plone_workers) | list }}'
      loop_control:
        loop_var: 'plone_instance_number'
      vars:
        plone_instance_name: 'instance{{ plone_instance_number | int + 1 }}'
        plone_instance_port: '{{ plone_base_port | int + plone_instance_number | int + 1 }}'
      tags:
        - dev

    - name: 'Run the tasks from the role plone_instance'
      ansible.builtin.include_role:
        name: plone_instance
      vars:
        plone_instance_name: 'worker'
        plone_instance_port: '{{ plone_base_port | int + 9 }}'
      when: plone_worker_instance

    - name: 'Create the supervisor configuration file'
      ansible.builtin.template:
        src: 'etc/supervisord.conf.j2'
        dest: '{{ plone_install_dir }}/etc/supervisord.conf'
        mode: '0600'
