---
- name: Test Plone
  hosts:
    - localhost
  connection: local
  vars:
    plone_base_port: 8080
    plone_workers: 2
  tasks:
    - name: Check if the instances are running
      ansible.builtin.uri:
        url: http://localhost:{{ plone_instance_port }}/@@ok
        status_code: 200
      loop: "{{ range(plone_workers) | list }}"
      loop_control:
        loop_var: plone_instance_number
      retries: 10
      delay: 1
      vars:
        plone_instance_port: "{{ plone_base_port | int + plone_instance_number | int + 1 }}"
