---
- name: Test Plone
  hosts:
    - localhost
  connection: local
  tasks:
    - name: Check if the instance is running
      ansible.builtin.uri:
        url: http://localhost:8080/@@ok
        status_code: 200
      retries: 10
      delay: 1
