---
name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache
          restore-keys: |
            ${{ runner.os }}-cache

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

      - name: Prepare the environment
        run: |
          mkdir -p etc/ansible
          echo "plone_install_dir: $HOME/plone" > etc/ansible/plone.yml

      - name: Install dependencies
        run: make

      - name: Start the instance
        run: $HOME/plone/bin/supervisord

      - name: Test the instances
        run: make test
